# Generated by Django 5.1.1 on 2025-03-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
