# Generated by Django 5.1.1 on 2025-04-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notifications_estado_notifications_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Titulo',
            field=models.CharField(max_length=100),
        ),
    ]
