# Generated by Django 5.1.1 on 2025-02-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermendad',
            name='name_disease',
            field=models.CharField(max_length=50, verbose_name='name of the disease'),
        ),
    ]
