# Generated by Django 5.1.1 on 2025-02-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedad', '0002_alter_enfermendad_name_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermendad',
            name='sintomas_disease',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sintomas of disease'),
        ),
    ]
