# Generated by Django 5.1.1 on 2025-02-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedad', '0003_enfermendad_sintomas_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermendad',
            name='name_disease',
            field=models.CharField(max_length=100, verbose_name='name of the disease'),
        ),
        migrations.AlterField(
            model_name='enfermendad',
            name='sintomas_disease',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sintomas of disease'),
        ),
    ]
