# Generated by Django 5.1.1 on 2025-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedad', '0006_alter_enfermendad_description_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermendad',
            name='sintomas_disease',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='sintomas of disease'),
        ),
    ]
