# Generated by Django 5.1.1 on 2025-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='Description of activity')),
                ('typeCoffee', models.IntegerField(max_length=10, verbose_name='type of coffee')),
            ],
        ),
    ]
