# Generated by Django 5.1.1 on 2025-01-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitys',
            old_name='description',
            new_name='activity_description',
        ),
        migrations.RenameField(
            model_name='activitys',
            old_name='name',
            new_name='activity_name',
        ),
    ]
