# Generated by Django 5.1.1 on 2025-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acividades', '0002_rename_description_activitys_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitys',
            name='typeCoffee',
            field=models.IntegerField(verbose_name='type of coffee'),
        ),
    ]
