# Generated by Django 5.1.1 on 2025-01-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acividades', '0006_alter_activitys_materials'),
        ('tipocafe', '0003_alter_typerice_description_alter_typerice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitys',
            name='typeCoffee',
        ),
        migrations.AddField(
            model_name='activitys',
            name='typeRice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipocafe.typerice', verbose_name='typeRice'),
            preserve_default=False,
        ),
    ]
