# Generated by Django 5.1.1 on 2025-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acividades', '0008_alter_activitys_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitys',
            name='materials',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Materials of activity'),
        ),
    ]
