# Generated by Django 5.1.1 on 2025-01-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acividades', '0009_alter_activitys_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitys',
            name='activity_name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
