# Generated by Django 5.1.1 on 2025-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typeRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name of rice')),
                ('description', models.CharField(max_length=50, verbose_name='description of rice')),
            ],
        ),
    ]
