# Generated by Django 5.1.1 on 2025-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typerice',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name of rice'),
        ),
    ]
