# Generated by Django 5.1.1 on 2025-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocafe', '0002_alter_typerice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typerice',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description of rice'),
        ),
        migrations.AlterField(
            model_name='typerice',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name of rice'),
        ),
    ]
