# Generated by Django 5.1.1 on 2025-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plague', models.CharField(max_length=25, verbose_name='name of the plague')),
                ('description_plague', models.CharField(max_length=150, verbose_name='description od the plague')),
                ('materials_plague', models.CharField(max_length=100, verbose_name='procedure materials')),
                ('procedure_plague', models.CharField(max_length=200, verbose_name='procedure of the plague')),
            ],
        ),
    ]
