# Generated by Django 5.1.1 on 2025-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaga', '0004_alter_plaga_materials_plague_alter_plaga_name_plague_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaga',
            name='description_plague',
            field=models.CharField(max_length=200, verbose_name='description od the plague'),
        ),
        migrations.AlterField(
            model_name='plaga',
            name='materials_plague',
            field=models.CharField(max_length=200, verbose_name='procedure materials'),
        ),
        migrations.AlterField(
            model_name='plaga',
            name='name_plague',
            field=models.CharField(max_length=200, verbose_name='name of the plague'),
        ),
        migrations.AlterField(
            model_name='plaga',
            name='sintomas_plague',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sintomas of plague'),
        ),
    ]
