# Generated by Django 5.1.1 on 2025-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaga', '0006_alter_plaga_name_plague_alter_plaga_sintomas_plague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaga',
            name='description_plague',
            field=models.CharField(max_length=250, verbose_name='description od the plague'),
        ),
        migrations.AlterField(
            model_name='plaga',
            name='sintomas_plague',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='sintomas of plague'),
        ),
    ]
