# Generated by Django 5.1.1 on 2025-01-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acividades', '0007_remove_activitys_typecoffee_activitys_typerice'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCalendario', models.IntegerField(verbose_name='id for calendary')),
                ('Fecha', models.DateField(verbose_name='date of activity')),
                ('clima', models.CharField(max_length=25, verbose_name='weather of day')),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acividades.activitys', verbose_name='activity of date')),
            ],
        ),
    ]
