# Generated by Django 5.1.1 on 2025-01-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='clima',
        ),
    ]
