# Generated by Django 5.1.1 on 2025-01-29 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_remove_event_clima'),
        ('inicioCalendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='idCalendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioCalendario.startcalendar', verbose_name='id of calendar'),
        ),
    ]
