# Generated by Django 5.1.1 on 2025-02-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedad', '0001_initial'),
        ('evento', '0003_alter_event_idcalendario'),
        ('plaga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='idEnfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enfermedad.enfermendad', verbose_name='id of enfermedad'),
        ),
        migrations.AddField(
            model_name='event',
            name='idPlaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plaga.plaga', verbose_name='id of plaga'),
        ),
    ]
