# Generated by Django 5.1.1 on 2025-02-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acividades', '0010_alter_activitys_activity_name'),
        ('evento', '0004_event_idenfermedad_event_idplaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='idActividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acividades.activitys', verbose_name='activity of date'),
        ),
    ]
